In [165]:
import pandas as pd
data=pd.read_csv("/content/MRF.NS (1).csv")
data.head()

         Date   Open   High    Low       Close   Adj Close  Volume
0  2002-07-01  910.0  910.0  880.0  897.599976  815.841370   426.0
1  2002-07-02  900.0  905.0  895.0  903.650024  821.340393   310.0
2  2002-07-03  910.0  910.0  900.0  906.700012  824.112366   336.0
3  2002-07-04  920.0  925.0  910.0  916.799988  833.292358   591.0
4  2002-07-05  915.0  935.0  910.0  927.299988  842.836182  1623.0

In [166]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2002-07-01,910.000000,910.0,880.000000,897.599976,815.841370,426.0
1,2002-07-02,900.000000,905.0,895.000000,903.650024,821.340393,310.0
2,2002-07-03,910.000000,910.0,900.000000,906.700012,824.112366,336.0
3,2002-07-04,920.000000,925.0,910.000000,916.799988,833.292358,591.0
4,2002-07-05,915.000000,935.0,910.000000,927.299988,842.836182,1623.0
...,...,...,...,...,...,...,...
4788,2021-09-23,80600.000000,80999.0,80001.546875,80220.703125,80220.703125,6530.0
4789,2021-09-24,80500.000000,80690.0,79055.046875,79456.500000,79456.500000,11095.0
4790,2021-09-27,79949.000000,82000.0,79144.648438,81893.398438,81893.398438,20927.0
4791,2021-09-28,81759.398438,81890.0,79810.000000,80488.601563,80488.601563,14053.0
4792,2021-09-29,80306.101563,80431.5,78901.046875,79056.703125,79056.703125,25732.0

In [167]:
data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,4776.000000,4776.000000,4776.000000,4776.000000,4776.000000,4776.000000
mean,24999.539156,25311.247821,24668.073474,24962.025982,24786.351552,9182.982831
std,27134.259259,27428.987474,26802.876610,27091.317441,27055.070703,12670.355564
min,779.450012,828.000000,779.450012,814.849976,743.103821,0.000000
25%,3260.000000,3316.437500,3199.750000,3242.549988,3112.166565,2266.250000
50%,9296.500000,9425.000000,9171.500000,9257.950195,9064.432617,5844.500000
75%,50399.237305,50946.750000,49711.187500,50195.249024,49910.255859,11105.250000
max,96770.000000,98599.953125,92750.000000,96973.851563,96910.757813,281075.000000

In [168]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4793 entries, 0 to 4792
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4793 non-null   object
 1   Open       4776 non-null   float64
 2   High       4776 non-null   float64
 3   Low        4776 non-null   float64
 4   Close      4776 non-null   float64
 5   Adj Close  4776 non-null   float64
 6   Volume     4776 non-null   float64
dtypes: float64(6), object(1)
memory usage: 262.2+ KB

In [169]:
data.isnull().sum()

Date          0
Open         17
High         17
Low          17
Close        17
Adj Close    17
Volume       17
dtype: int64

In [170]:
df=data.copy()

In [171]:
#fill the null values with mean

col=["Open","High","Low","Close","Adj Close","Volume"]
for i in col:
  df[i].fillna(df[i].mean(), inplace=True)

<ipython-input-171-458afc45e44c>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mean(), inplace=True)

In [172]:
df[col].isnull().sum()

Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [173]:
df.head()

         Date   Open   High    Low       Close   Adj Close  Volume
0  2002-07-01  910.0  910.0  880.0  897.599976  815.841370   426.0
1  2002-07-02  900.0  905.0  895.0  903.650024  821.340393   310.0
2  2002-07-03  910.0  910.0  900.0  906.700012  824.112366   336.0
3  2002-07-04  920.0  925.0  910.0  916.799988  833.292358   591.0
4  2002-07-05  915.0  935.0  910.0  927.299988  842.836182  1623.0

In [174]:
"""import numpy as np
#data splitting

x=df[['Open','High','Low','Close','Volume']]
y=np.where(df["Adj Close"].shift(1) > df["Adj Close"],0,1) """

'import numpy as np\n#data splitting\n\nx=df[[\'Open\',\'High\',\'Low\',\'Close\',\'Volume\']]\ny=np.where(df["Adj Close"].shift(1) > df["Adj Close"],0,1) '

In [175]:
#x.shape

In [176]:
#print(y)

In [177]:
"""import statsmodels.api as sm

log_reg = sm.Logit(y, x).fit()
"""

'import statsmodels.api as sm\n\nlog_reg = sm.Logit(y, x).fit()\n'

In [178]:
#print(log_reg.summary())

In [179]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import (confusion_matrix , accuracy_score)
import numpy as np

#features splitting
x=df[['Open','High','Low','Close','Volume']]
y=np.where(df["Adj Close"].shift(1) > df["Adj Close"],0,1)

#data splitting
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=52)

In [180]:
#model initialization
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [181]:
# Make predictions
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

In [182]:
print(y_pred)

[1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0
 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1
 0 0 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1
 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1
 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1
 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 1 0 1
 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0
 1 0 1 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0
 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1 0
 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1
 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0
 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1
 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 1
 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0
 1 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 0 1 0 1
 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1
 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1
 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1
 1 1 1 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 1 1 1 0
 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0
 1 0 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0]

In [183]:
#from sklearn.metrics import (confusion_matrix , accuracy_score)

#confusion matrix
cm=confusion_matrix(  y_test, y_pred)
print("confusion matrix : \n ",cm)

#accuracy score of the model
print('Test accuracy= ', accuracy_score( y_test, y_pred))

confusion matrix :
  [[403  63]
 [122 371]]
Test accuracy=  0.8070907194994786

In [184]:
#accuracy statistics
from sklearn import metrics
from sklearn.metrics import classification_report

print("Accuracy score: ",metrics.accuracy_score(y_test, y_pred))

#create classification report
class_report=classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy score:  0.8070907194994786
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.86      0.81       466
           1       0.85      0.75      0.80       493

    accuracy                           0.81       959
   macro avg       0.81      0.81      0.81       959
weighted avg       0.81      0.81      0.81       959

In [185]:
# Evaluate the model
"""
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)

# Print the evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"AUC-ROC: {auc}")
"""

'\naccuracy = accuracy_score(y_test, y_pred)\nprecision = precision_score(y_test, y_pred)\nrecall = recall_score(y_test, y_pred)\nf1 = f1_score(y_test, y_pred)\nauc = roc_auc_score(y_test, y_pred_proba)\n\n# Print the evaluation metrics\nprint(f"Accuracy: {accuracy}")\nprint(f"Precision: {precision}")\nprint(f"Recall: {recall}")\nprint(f"F1 Score: {f1}")\nprint(f"AUC-ROC: {auc}")\n'

#0r

In [188]:
# defining Independent and Dependent Variables

# X is Independent Variables
Xtrain = df[["Open", "High", "Low", "Close"]]


# y is the dependent variable

ytrain =np.where( df['Adj Close'].shift(1) > df['Adj Close'],0,1)

In [186]:
import statsmodels.api as sm
from sklearn.metrics import (confusion_matrix,accuracy_score)
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
Xtrain, Xtest, ytrain, ytest = train_test_split(df[["Open", "High", "Low", "Close"]],
                                                np.where(df['Adj Close'].shift(1) > df['Adj Close'], 0, 1),
                                                test_size=0.2, # Adjust test_size as needed
                                                random_state=42)  # Set random_state for reproducibility

log_reg = sm.Logit(ytrain, Xtrain).fit()

#printing the summary table
print(log_reg.summary())

Optimization terminated successfully.
         Current function value: 0.453239
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 3834
Model:                          Logit   Df Residuals:                     3830
Method:                           MLE   Df Model:                            3
Date:                Fri, 24 Jan 2025   Pseudo R-squ.:                  0.3459
Time:                        06:52:17   Log-Likelihood:                -1737.7
converged:                       True   LL-Null:                       -2656.5
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Open          -0.0066      0.000    -17.255      0.000      -0.007      -0.006
High          -0.0020      0.000     -5.916      0.000      -0.003      -0.001
Low           -0.0021      0.000     -5.617      0.000      -0.003      -0.001
Close          0.0107      0.001     19.570      0.000       0.010       0.012
==============================================================================

In [191]:
Xtrain.shape

(4793, 4)

In [192]:
ytrain.shape

(4793,)

In [194]:
Xtest.shape

(959, 4)

In [195]:
ytest.shape

(959,)

In [193]:
print(ytrain)

[1 1 1 ... 1 0 0]

In [196]:
# Make predictions on the test set
prediction = log_reg.predict(Xtest)

In [197]:
print(prediction)

561     0.386258
893     0.402355
1684    0.495441
705     0.418164
1873    0.464112
          ...
1859    0.475564
4283    0.999981
650     0.454038
2302    0.160404
708     0.441114
Length: 959, dtype: float64

In [198]:
prediction = (prediction > 0.5).astype(int)  # Convert probabilities to class labels (0 or 1)

In [199]:
print(prediction)

561     0
893     0
1684    0
705     0
1873    0
       ..
1859    0
4283    1
650     0
2302    0
708     0
Length: 959, dtype: int64

In [200]:
cm=confusion_matrix(ytest,prediction)
print(f"confusion matrix : \n {cm}")

confusion matrix :
 [[422  72]
 [ 98 367]]

In [201]:
print("accuracy score: ",accuracy_score(ytest,prediction))

accuracy score:  0.8227320125130344

In [202]:
# accuracy statistics

from sklearn import metrics
print( 'Accuracy Score:',metrics.accuracy_score(ytest, prediction))

print( 'Precision Score:',metrics.precision_score(ytest, prediction))
print( 'Recall Score:',metrics.recall_score(ytest, prediction))
print( 'F1 Score:',metrics.f1_score(ytest, prediction))

Accuracy Score: 0.8227320125130344
Precision Score: 0.835990888382688
Recall Score: 0.789247311827957
F1 Score: 0.8119469026548672

In [203]:
#classification report

class_report=classification_report(ytest, prediction)
print(class_report)

              precision    recall  f1-score   support

           0       0.81      0.85      0.83       494
           1       0.84      0.79      0.81       465

    accuracy                           0.82       959
   macro avg       0.82      0.82      0.82       959
weighted avg       0.82      0.82      0.82       959