In [140]:
#importing neccesary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [141]:
#read the data

data=pd.read_csv("/content/MRF.NS.csv")
data.head()

         Date   Open   High    Low       Close   Adj Close  Volume
0  2002-07-01  910.0  910.0  880.0  897.599976  815.841370   426.0
1  2002-07-02  900.0  905.0  895.0  903.650024  821.340393   310.0
2  2002-07-03  910.0  910.0  900.0  906.700012  824.112366   336.0
3  2002-07-04  920.0  925.0  910.0  916.799988  833.292358   591.0
4  2002-07-05  915.0  935.0  910.0  927.299988  842.836182  1623.0

In [142]:
data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,4776.000000,4776.000000,4776.000000,4776.000000,4776.000000,4776.000000
mean,24999.539156,25311.247821,24668.073474,24962.025982,24786.351552,9182.982831
std,27134.259259,27428.987474,26802.876610,27091.317441,27055.070703,12670.355564
min,779.450012,828.000000,779.450012,814.849976,743.103821,0.000000
25%,3260.000000,3316.437500,3199.750000,3242.549988,3112.166565,2266.250000
50%,9296.500000,9425.000000,9171.500000,9257.950195,9064.432617,5844.500000
75%,50399.237305,50946.750000,49711.187500,50195.249024,49910.255859,11105.250000
max,96770.000000,98599.953125,92750.000000,96973.851563,96910.757813,281075.000000

In [143]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4793 entries, 0 to 4792
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4793 non-null   object
 1   Open       4776 non-null   float64
 2   High       4776 non-null   float64
 3   Low        4776 non-null   float64
 4   Close      4776 non-null   float64
 5   Adj Close  4776 non-null   float64
 6   Volume     4776 non-null   float64
dtypes: float64(6), object(1)
memory usage: 262.2+ KB

In [144]:
data.shape

(4793, 7)

In [145]:
data.isnull().sum()

Date          0
Open         17
High         17
Low          17
Close        17
Adj Close    17
Volume       17
dtype: int64

In [146]:
#filling the null vallues with mean
cols=["Open","High","Low","Close","Adj Close","Volume"]
for col in cols:
  data[col]=data[col].fillna(data[col].mean())

In [147]:
data.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [148]:
#creating feature and target variables

x=data[["Open","High","Low","Close",]]

y=np.where(data["Adj Close"].shift(-1) > data["Adj Close"],0,1)

In [149]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [150]:
#data spliiting x and y for training

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=52)

In [151]:
#naive bayes model initialization
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

nb=GaussianNB()
model=nb.fit(x_train, y_train)

In [152]:
y_pred=model.predict(x_test)

In [153]:
y_pred = (y_pred > 0.5).astype(int)

In [154]:
accuracy=accuracy_score(y_test, y_pred)
accuracy

0.5255474452554745

In [155]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[ 78, 375],
       [ 80, 426]])

In [156]:
cl_report = classification_report(y_test, y_pred)
print(cl_report)

              precision    recall  f1-score   support

           0       0.49      0.17      0.26       453
           1       0.53      0.84      0.65       506

    accuracy                           0.53       959
   macro avg       0.51      0.51      0.45       959
weighted avg       0.51      0.53      0.46       959

In [157]:
#or

In [158]:
#model initialization

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()
model=lr.fit(x_train, y_train)

In [159]:
y_pred=model.predict(x_test)

In [160]:
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [161]:
y_pred = (y_pred > 0.5).astype(int)

In [162]:
accuracy=accuracy_score(y_test, y_pred)
accuracy

0.5245046923879041

In [163]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[  1, 452],
       [  4, 502]])

In [164]:
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.20      0.00      0.00       453
           1       0.53      0.99      0.69       506

    accuracy                           0.52       959
   macro avg       0.36      0.50      0.35       959
weighted avg       0.37      0.52      0.36       959

In [165]:
import statsmodels.api as sm

model=sm.Logit(y_train, x_train).fit()

Optimization terminated successfully.
         Current function value: 0.692968
         Iterations 3

In [166]:
pred=model.predict(x_test)

In [167]:
pred = (pred > 0.5).astype(int)

In [168]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[  1, 452],
       [  4, 502]])

In [169]:
accu=accuracy_score(y_test, pred)
accu

0.529718456725756